export const TITLE_ASYNC_REQUEST = `TITLE/ASYNC_REQUEST`;
export const TITLE_REQUEST_SUCCESS = `TITLE/REQUEST_SUCCESS`;
export const TITLE_REQUEST_ERROR = `TITLE/REQUEST_ERROR`;
export const TITLE_IS_LOADING = `TITLE/IS_LOADING`;
export const TITLE_GET_REQUEST = `TITLE/GET`;
export const TITLE_GET_SUCCESS = `TITLE/GET_SUCCESS`;

export const ADD_MOVIE_WISHLIST = `USER/ADD_WISHLIST`;
export const REMOVE_MOVIE_WISHLIST = `USER/REMOVE_WISHLIST`;
